name: "Deploy to Cloudflare"

on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
  deploy-ci:
    runs-on: ubuntu-latest
    name: Deploy (CI)
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          command: deploy --config wrangler-ci.toml
