name: Conventional Commit
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}